"use client";
import { FormEvent, useState } from "react";
import { FeatureLayout } from "../components/FeatureLayout";
import { Modal } from "../components/Modal";
import { StoredItem, useLocalCollection } from "../hooks/useLocalCollection";
type Notice = StoredItem & { title: string; content: string; author: string; important: boolean };
export function NoticeBoard() {
  const store = useLocalCollection<Notice>("tsv-notices"); const [open, setOpen] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); store.add({ title: String(data.get("title")), content: String(data.get("content")), author: String(data.get("author")), important: data.get("important") === "on" }); setOpen(false); }
  return <FeatureLayout icon="📢" title="공지사항" description="새로운 소식과 꼭 확인해야 할 내용을 공유합니다." action={<button className="primary-button" onClick={() => setOpen(true)}>＋ 새 공지 추가</button>}><section className="content-panel">{store.items.length === 0 ? <div className="empty-state"><b>등록된 공지가 없습니다.</b><span>첫 공지사항을 추가해 보세요.</span></div> : <div className="notice-list">{store.items.map((notice) => <article className="notice-item" key={notice.id}><div>{notice.important && <span className="tag important">중요</span>}<h2>{notice.title}</h2><p>{notice.content}</p><small>{notice.author} · {new Date(notice.createdAt).toLocaleDateString("ko-KR")}</small></div><button className="danger-button" onClick={() => store.remove(notice.id)} aria-label={`${notice.title} 삭제`}>삭제</button></article>)}</div>}</section>{open && <Modal title="새 공지사항" onClose={() => setOpen(false)}><form className="entry-form" onSubmit={submit}><label>제목<input name="title" required maxLength={80} autoFocus /></label><label>작성자<input name="author" required maxLength={30} /></label><label>내용<textarea name="content" required rows={6} maxLength={1000} /></label><label className="checkbox-label"><input name="important" type="checkbox" /> 중요 공지로 표시</label><div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>취소</button><button className="primary-button">저장</button></div></form></Modal>}</FeatureLayout>;
}
